/// RouterConfigEngine
/// Generates router initial configuration including hostname,
/// interfaces, passwords, and banner.

class RouterConfigEngine {
  RouterConfigEngine._();

  /// Generates a base router configuration template.
  static String baseConfig({
    required String hostname,
    required List<RouterInterface> interfaces,
    String? enableSecret,
    String? banner,
    bool sshEnabled = true,
    String? domainName,
    String? username,
    String? password,
  }) {
    final sb = StringBuffer();

    sb.writeln('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');
    sb.writeln('! Base Router Configuration');
    sb.writeln('! Generated by Network Engineering Assistant');
    sb.writeln('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');
    sb.writeln();

    // Hostname
    sb.writeln('hostname $hostname');
    sb.writeln('!');

    // Disable DNS lookup (avoids delay on typos)
    sb.writeln('no ip domain-lookup');
    sb.writeln('!');

    // Security
    if (enableSecret != null) {
      sb.writeln('enable secret $enableSecret');
      sb.writeln('service password-encryption');
      sb.writeln('!');
    }

    // SSH
    if (sshEnabled && domainName != null) {
      sb.writeln('ip domain-name $domainName');
      if (username != null && password != null) {
        sb.writeln('username $username privilege 15 secret $password');
      }
      sb.writeln('crypto key generate rsa modulus 2048');
      sb.writeln('ip ssh version 2');
      sb.writeln('!');
      sb.writeln('line vty 0 4');
      sb.writeln(' login local');
      sb.writeln(' transport input ssh');
      sb.writeln('!');
    }

    // Console line
    sb.writeln('line con 0');
    sb.writeln(' logging synchronous');
    if (password != null) sb.writeln(' password $password');
    sb.writeln(' exec-timeout 30 0');
    sb.writeln('!');

    // Banner
    if (banner != null) {
      sb.writeln('banner motd ^');
      sb.writeln(banner);
      sb.writeln('^');
      sb.writeln('!');
    }

    // Interfaces
    for (final iface in interfaces) {
      sb.writeln('interface ${iface.name}');
      if (iface.description != null) {
        sb.writeln(' description ${iface.description}');
      }
      if (iface.ipAddress != null && iface.subnetMask != null) {
        sb.writeln(' ip address ${iface.ipAddress} ${iface.subnetMask}');
      }
      if (iface.isLoopback) {
        // Loopback is always up
      } else {
        sb.writeln(' no shutdown');
      }
      sb.writeln('!');
    }

    sb.writeln('end');
    return sb.toString();
  }

  /// Returns a list of common Cisco interface name abbreviations.
  static const List<String> commonInterfaces = [
    'GigabitEthernet0/0',
    'GigabitEthernet0/1',
    'GigabitEthernet0/2',
    'FastEthernet0/0',
    'FastEthernet0/1',
    'Serial0/0/0',
    'Serial0/0/1',
    'Loopback0',
    'Loopback1',
  ];
}

/// RouterInterface
/// Represents a single router interface entry.
class RouterInterface {
  final String name;
  final String? description;
  final String? ipAddress;
  final String? subnetMask;
  final bool isLoopback;

  const RouterInterface({
    required this.name,
    this.description,
    this.ipAddress,
    this.subnetMask,
    this.isLoopback = false,
  });

  factory RouterInterface.loopback(int id, String ip, String mask) =>
      RouterInterface(
        name: 'Loopback$id',
        ipAddress: ip,
        subnetMask: mask,
        isLoopback: true,
        description: 'Loopback interface $id',
      );
}
